/***	MM.H - MasterMind definition file
 *
 *	(c) 1991, Benjamin W. Slivka
 */


// Menu IDs

#define IDM_OPTIONS	    20
#define     IDM_SETTINGS    21
#define     IDM_ABOUT	    22

#define IDD_ABOUT	   100


// Control IDs

#define IDC_GUESS	    30
#define IDC_NEW_GAME	    31


// String IDs

#define IDS_APP_TITLE	    10

#define IDS_GUESS	    20
#define IDS_NEW_GAME	    21

#define IDS_RESIGN	    22


// Cursor IDs

#define CUR_OVER_WELL	    40
#define CUR_DRAG	    41
#define CUR_DRAG_OVER	    42


//***	Color definitions

#define CLR_BLACK   (RGB(0x00,0x00,0x00))
#define CLR_BLUE    (RGB(0x00,0x00,0xFF))
#define CLR_GREEN   (RGB(0x00,0xFF,0x00))
#define CLR_YELLOW  (RGB(0xFF,0xFF,0x00))
#define CLR_RED     (RGB(0xFF,0x00,0x00))
#define CLR_WHITE   (RGB(0xFF,0xFF,0xFF))
